# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    echo "Adding Qt5 dev environment"
    sudo apt-get install git qtbase5-dev libqt5svg5-dev qt5-default qtcreator pax-utils tree -y
    
    echo "Generating makefiles"
    qmake

    ls -l translations
    
    echo "Updating translation books and regenerating binary translations"
    echo Update TS strings from the source code
    make ts
    echo Update QM from the updated TS
    make qm

    echo "Generating a pull request with the updated /translations/"
    ls -l translations/
    echo Pre Status
    git status -sb
    echo Post Status
    git add -A translations
    git status -sb
    ls -l

    ls -l translations

    echo "Generating makefiles"
    qmake

    echo "Done"
  displayName: 'Run a multi-line script'
