# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- script: |
    sudo apt-get install git qtbase5-dev libqt5svg5-dev qt5-default qtcreator pax-utils tree -y
    qmake
    echo Update QM binaries from existing TS
    make qm
    echo Update TS strings from the source code
    make ts
    echo Update QM from the updated TS
    make qm
    ls -l translations/
    echo Pre Status
    git status -sb
    echo Post Status
    git add -a translations
    git status -sb
    ls -l
  displayName: 'Run a multi-line script'
